# usermod -aG docker gitlab-runner

stages:
  - build
  - deploy

variables:
  PROJECT_NAME: client-server
  REGISTRY_URL: registry.cn-hongkong.aliyuncs.com/need_cash

build_prod_docker:
  stage: build
  before_script:
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:master
    - docker push $REGISTRY_URL/$PROJECT_NAME:master
  only:
    - master
  tags:
    - builder

build_trial_docker:
  stage: build
  before_script:
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:trial
    - docker push $REGISTRY_URL/$PROJECT_NAME:trial
  only:
    - trial
  tags:
    - builder


# 构建生产环境
deploy_prod:
  stage: deploy
  script:
    - docker stack deploy -c deploy.prod.yml --with-registry-auth $PROJECT_NAME
  only:
    - master
  tags:
    - builder

# 测试环境
deploy_test:
  stage: deploy
  script:
    - docker stack deploy -c deploy.trial.yml --with-registry-auth $PROJECT_NAME
  only:
    - trial
  tags:
    - builder

build_docker:
  stage: build
  before_script:
  #    - git submodule sync --recursive
  #    - git submodule update --init --recursive
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:latest
    - docker push $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY_URL/$PROJECT_NAME:latest
  only:
    - tags
  tags:
    - builder

deploy_docker:
  stage: deploy
  script:
    - echo SUCCESSd
  only:
    - tags
  tags:
    - builder
